version: '3'
 
services:
    apache_img:
        container_name: ${COMPOSE_PROJECT_NAME}_apache_con
        build:
            context: ./apache
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        volumes:
            - ../logs/apache:${APACHE_ROOT_DIR}/logs
            - ../public_html:${APACHE_ROOT_DIR}/htdocs
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        depends_on:
            - mysql_img
            - php_img
        networks:
            private_net:
                ipv4_address: ${APACHE_PRIVATE_IP}
            public_net:
                ipv4_address: ${APACHE_IP}
        environment:
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
            - PHP_IP=${PHP_IP}
            - PHP_APP_DIR=${PHP_APP_DIR}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
            - SET_CONTAINER_TIMEZONE=true
            - CONTAINER_TIMEZONE=${CONTAINER_TIMEZONE}
    mysql_img:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql_con
        build:
            context: ./mysql
            args:
                - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
                - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
        volumes:
            - ../logs/mysql:${MYSQL_LOG_DIR}
            - ../database:${MYSQL_DATA_DIR}
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            private_net:
                ipv4_address: ${MYSQL_PRIVATE_IP}
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_CONTAINER_USER: ${MYSQL_CONTAINER_USER}
            MYSQL_CONTAINER_GROUP: ${MYSQL_CONTAINER_GROUP}
            SET_CONTAINER_TIMEZONE: 'true'
            CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
    php_img:
        container_name: ${COMPOSE_PROJECT_NAME}_php_con
        build:
            context: ./php
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - ../public_html:${PHP_APP_DIR}
            - ../logs/php:${PHP_ROOT_DIR}/logs
            - "/etc/timezone:/etc/timezone:ro"
            - "/etc/localtime:/etc/localtime:ro"
        networks:
            private_net:
                ipv4_address: ${PHP_PRIVATE_IP}
            public_net:
                ipv4_address: ${PHP_IP}
        environment:
            PHP_ROOT_DIR: ${PHP_ROOT_DIR}
            APACHE_IP: ${APACHE_IP}
            APACHE_EXPOSED_PORT: ${APACHE_EXPOSED_PORT}
            WEB_USER: ${WEB_USER}
            WEB_GROUP: ${WEB_GROUP}
            MYSQL_IP: ${MYSQL_IP}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            SET_CONTAINER_TIMEZONE: 'true'
            CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE}
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
    private_net:
        driver: bridge
        internal: true
        ipam:
            driver: default
            config:
                - subnet: ${PRIVATE_NETWORK_SUBNET}